version: "2"

services:

     sql-server:
        image: testeaec/aec-teste-sql-server:latest
        container_name: aec-teste-sql-server
        build: 
            dockerfile: ./sql/Dockerfile
        environment:
            SA_PASSWORD: "aecTeste@123"
            ACCEPT_EULA: "Y" 
        ports: 
           - "1433:1433" 