version: "1"

services:

     web-api:
         image: testeaec/aec-teste-api:latest
         container_name: aec-teste-api
         build: 
            dockerfile: ./AeC_Teste.API/Dockerfile
         restart: always
         environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001

     sql-server:
        image: testeaec/aec-teste-sql-server:latest
        container_name: aec-teste-sql-server
        build: 
            dockerfile: ./sql/Dockerfile
        environment:
            SA_PASSWORD: "aecTeste@123"
            ACCEPT_EULA: "Y" 
        ports: 
           - "1433:1433" 